### ISSUE TITLE
Error encountered: For input string: "2810-2814"

### ISSUE THREAD

**Issue by enriquead1** [yeastrc/proxl-import-api#1]
I am running MeroX 2.0 from Ubuntu 23.10 using java-8-openjdk-amd64 (It does not work with java 11). Everything seems to be okay with the analysis of demo data, but when I try to use merox2ProxlXML.jar, there is the following error:

Error encountered:
For input string: "2810-2814"

My command:
/usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar ../merox2ProxlXML.jar -r ./StavroX_Test.zhrm -f StavroX_Test.fasta -o results.xml

(Also tried /usr/lib/jvm/java-11-openjdk-amd64/bin/java, with the same result)

**Comment by mriffle** [comment]
Hi, based on the filenames in your command, it looks like you are using StavroX. Can you try the StavroX converter? It's here: https://github.com/yeastrc/proxl-import-stavrox
